export const companies = [
  {
    id: 1,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN GIAO HÀNG TIẾT KIỆM",
    major: "cong ty",
    website: "https://giaohangtietkiem.vn/",
    employees: "10000+ employees",
    introduction:
      "Công ty CP Giao Hàng Tiết Kiệm (GHTK) là công ty công nghệ hoạt động trong lĩnh vực Logistics...",
    contact: "Tòa nhà GHTK Building - Số 8 Phạm Hùng, Mễ Trì, Từ Liêm, Hà Nội",
  },
  {
    id: 2,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY ASUS",
    major: "cong ty",
    website: "https://asus.com/",
    employees: "10000+ employees",
    introduction:
      "ASUS là một trong những tập đoàn công nghệ hàng đầu thế giới, chuyên sản xuất phần cứng và thiết bị điện tử.",
    contact: "Toà nhà Bitexco, TP. Hồ Chí Minh",
  },
  {
    id: 3,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY TNHH TIKI",
    major: "cong ty",
    website: "https://tiki.vn",
    employees: "5000+ employees",
    introduction:
      "Tiki là nền tảng thương mại điện tử hàng đầu tại Việt Nam, cung cấp hàng triệu sản phẩm chất lượng.",
    contact: "52 Út Tịch, Phường 4, Quận Tân Bình, TP.HCM",
  },
  {
    id: 4,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN VNG",
    major: "cong ty",
    website: "https://vng.com.vn",
    employees: "3000+ employees",
    introduction:
      "VNG là công ty công nghệ hàng đầu Việt Nam chuyên về nội dung số, mạng xã hội và trò chơi trực tuyến.",
    contact: "VNG Campus, TP. Hồ Chí Minh",
  },
  {
    id: 5,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY TNHH GRAB VIỆT NAM",
    major: "cong ty",
    website: "https://grab.com/vn",
    employees: "10000+ employees",
    introduction:
      "Grab là nền tảng công nghệ đa dịch vụ, cung cấp các giải pháp vận chuyển, giao nhận và thanh toán.",
    contact: "Saigon Centre, Quận 1, TP.HCM",
  },
  {
    id: 6,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN BE GROUP",
    major: "cong ty",
    website: "https://be.com.vn",
    employees: "2000+ employees",
    introduction:
      "Be là ứng dụng gọi xe công nghệ thuần Việt, cung cấp các dịch vụ vận chuyển, giao hàng và tài chính.",
    contact: "Hoàng Văn Thụ, Quận Tân Bình, TP.HCM",
  },
  {
    id: 7,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN LAZADA VIỆT NAM",
    major: "cong ty",
    website: "https://lazada.vn",
    employees: "5000+ employees",
    introduction:
      "Lazada là một trong những sàn thương mại điện tử lớn nhất Đông Nam Á, trực thuộc Alibaba Group.",
    contact: "Tháp e.Town Central, Quận 4, TP.HCM",
  },
  {
    id: 8,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY VINSMART",
    major: "cong ty",
    website: "https://vinsmart.net",
    employees: "4000+ employees",
    introduction:
      "VinSmart là công ty công nghệ thuộc Tập đoàn Vingroup, tập trung vào sản xuất thiết bị điện tử thông minh.",
    contact: "Khu Công nghệ cao Hòa Lạc, Hà Nội",
  },
  {
    id: 9,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN FPT",
    major: "cong ty",
    website: "https://fpt.com.vn",
    employees: "40000+ employees",
    introduction:
      "FPT là tập đoàn công nghệ hàng đầu Việt Nam hoạt động trong lĩnh vực CNTT, viễn thông và giáo dục.",
    contact: "FPT Tower, Cầu Giấy, Hà Nội",
  },
  {
    id: 10,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN VNPAY",
    major: "cong ty",
    website: "https://vnpay.vn",
    employees: "3000+ employees",
    introduction:
      "VNPAY cung cấp các giải pháp thanh toán điện tử cho doanh nghiệp và người dùng cá nhân.",
    contact: "Tầng 7, Tòa nhà Times Tower, Hà Nội",
  },
  {
    id: 11,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN MOCA",
    major: "cong ty",
    website: "https://moca.vn",
    employees: "500+ employees",
    introduction:
      "Moca là ví điện tử tích hợp với ứng dụng Grab, cung cấp dịch vụ thanh toán không dùng tiền mặt.",
    contact: "Keangnam Hanoi Landmark Tower, Hà Nội",
  },
  {
    id: 12,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN VEXERE",
    major: "cong ty",
    website: "https://vexere.com",
    employees: "300+ employees",
    introduction:
      "VeXeRe là nền tảng đặt vé xe khách trực tuyến lớn nhất Việt Nam, kết nối với hơn 1000 nhà xe.",
    contact: "Lê Quang Định, Bình Thạnh, TP.HCM",
  },
  {
    id: 13,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY CỔ PHẦN CỐC CỐC",
    major: "cong ty",
    website: "https://coccoc.com",
    employees: "400+ employees",
    introduction:
      "Cốc Cốc là công ty công nghệ phát triển trình duyệt và công cụ tìm kiếm dành riêng cho người Việt.",
    contact: "Cầu Giấy, Hà Nội",
  },
  {
    id: 14,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY TNHH SHOPEE VIỆT NAM",
    major: "cong ty",
    website: "https://shopee.vn",
    employees: "7000+ employees",
    introduction:
      "Shopee là nền tảng thương mại điện tử hàng đầu Đông Nam Á, cung cấp hàng triệu sản phẩm đa dạng.",
    contact: "Saigon Centre, Quận 1, TP.HCM",
  },
  {
    id: 15,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY TNHH BAEMIN VIỆT NAM",
    major: "cong ty",
    website: "https://baemin.vn",
    employees: "1000+ employees",
    introduction:
      "Baemin là ứng dụng giao đồ ăn nhanh phát triển bởi Woowa Brothers, có mặt tại nhiều thành phố lớn.",
    contact: "Lê Lai, Quận 1, TP.HCM",
  },
  {
    id: 16,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY TNHH NOW",
    major: "cong ty",
    website: "https://now.vn",
    employees: "2000+ employees",
    introduction:
      "Now là ứng dụng đặt đồ ăn trực tuyến, mua sắm và giao hàng, trực thuộc Foody Corporation.",
    contact: "Quận Phú Nhuận, TP.HCM",
  },
  {
    id: 17,
    coverImage: "/cover.jpg",
    logoImage: "/avt.jpg",
    title: "CÔNG TY TNHH TECHCOMBANK",
    major: "cong ty",
    website: "https://techcombank.com.vn",
    employees: "11000+ employees",
    introduction:
      "Techcombank là một trong những ngân hàng thương mại cổ phần lớn nhất tại Việt Nam.",
    contact: "Tòa nhà Techcombank, Lý Thường Kiệt, Hà Nội",
  },
];
