export const jobs = [
  {
    id: 1,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 2,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "ABC - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 3,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 4,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 5,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 6,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 7,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 8,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 9,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
  {
    id: 10,
    logo: "/cover.jpg",
    name: "logo",
    title:
      "Sales staff - Enrollment consultant - Telesales (income from 20-50 million/month) - Stellar Garden - Thanh Xuan Hanoi",
    company: "PALFISH INTERNATIONAL SCHOOL SINGAPORE - VIETNAM",
    province: "Ho Chi Minh",
    experience: "1 year",
    salary: "10.000.000",
    postedAt: "1 day ago",
  },
];
